# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: windows-latest

steps:
- task: BatchScript@1
  inputs:
    filename: 'nckr.PowerPlatform.IsvHub.Solution/spkl/pack.bat'
    workingFolder: 'nckr.PowerPlatform.IsvHub.Solution/spkl'

- task: CopyFiles@2
  inputs:
    Contents: '**\*.zip'
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
